### ISSUE TITLE
这个脚本的存在是不是说明一般网页都可以探测到用户的暴力猴安装脚本列表？

### ISSUE THREAD

**Issue by woyaojizhu8** [violentmonkey/vm-detector#2]

**Comment by gera2ld** [comment]
不是。

1. 有白名单控制，目前接口只对 GreasyFork 开放： <https://github.com/violentmonkey/violentmonkey/blob/816f02d01b68bfd18048b87c5aad65b35c23d593/src/injected/web/index.js#L90-L94>

2. 页面需要提供正确的 name 和 namespace 才能知道脚本是否安装，可以认为是无法遍历出所有脚本的。

**Comment by ivysrono** [comment]
原来就是这个原因导致的 #1 啊。
难怪怎么都获取不到 external
https://github.com/violentmonkey/vm-detector/blob/master/vm-detector.user.js#L50
